{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "45ada697",
   "metadata": {},
   "outputs": [
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'requests'",
     "output_type": "error",
     "traceback": [
      "\u001b[31m---------------------------------------------------------------------------\u001b[39m",
      "\u001b[31mModuleNotFoundError\u001b[39m                       Traceback (most recent call last)",
      "\u001b[36mCell\u001b[39m\u001b[36m \u001b[39m\u001b[32mIn[1]\u001b[39m\u001b[32m, line 2\u001b[39m\n\u001b[32m      1\u001b[39m \u001b[38;5;28;01mimport\u001b[39;00m pandas \u001b[38;5;28;01mas\u001b[39;00m pd\n\u001b[32m----> \u001b[39m\u001b[32m2\u001b[39m \u001b[38;5;28;01mimport\u001b[39;00m requests\n\u001b[32m      3\u001b[39m \n\u001b[32m      4\u001b[39m \u001b[38;5;66;03m# Fetch the data.\u001b[39;00m\n\u001b[32m      5\u001b[39m df = pd.read_csv(\u001b[33m\"https://ourworldindata.org/grapher/countries-democracies-autocracies-row.csv?v=1&csvType=full&useColumnShortNames=true\"\u001b[39m, storage_options = {\u001b[33m'User-Agent'\u001b[39m: \u001b[33m'Our World In Data data fetch/1.0'\u001b[39m})\n",
      "\u001b[31mModuleNotFoundError\u001b[39m: No module named 'requests'"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import requests\n",
    "\n",
    "# Fetch the data.\n",
    "df = pd.read_csv(\"https://ourworldindata.org/grapher/countries-democracies-autocracies-row.csv?v=1&csvType=full&useColumnShortNames=true\", storage_options = {'User-Agent': 'Our World In Data data fetch/1.0'})\n",
    "\n",
    "# Fetch the metadata\n",
    "metadata = requests.get(\"https://ourworldindata.org/grapher/countries-democracies-autocracies-row.metadata.json?v=1&csvType=full&useColumnShortNames=true\").json()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "cf8bc76e",
   "metadata": {},
   "outputs": [
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'requests'",
     "output_type": "error",
     "traceback": [
      "\u001b[31m---------------------------------------------------------------------------\u001b[39m",
      "\u001b[31mModuleNotFoundError\u001b[39m                       Traceback (most recent call last)",
      "\u001b[36mCell\u001b[39m\u001b[36m \u001b[39m\u001b[32mIn[1]\u001b[39m\u001b[32m, line 2\u001b[39m\n\u001b[32m      1\u001b[39m \u001b[38;5;28;01mimport\u001b[39;00m pandas \u001b[38;5;28;01mas\u001b[39;00m pd\n\u001b[32m----> \u001b[39m\u001b[32m2\u001b[39m \u001b[38;5;28;01mimport\u001b[39;00m requests\n\u001b[32m      3\u001b[39m \n\u001b[32m      4\u001b[39m \u001b[38;5;66;03m# Fetch the data.\u001b[39;00m\n\u001b[32m      5\u001b[39m df = pd.read_csv(\u001b[33m\"https://ourworldindata.org/grapher/countries-democracies-autocracies-row.csv?v=1&csvType=full&useColumnShortNames=true\"\u001b[39m, storage_options = {\u001b[33m'User-Agent'\u001b[39m: \u001b[33m'Our World In Data data fetch/1.0'\u001b[39m})\n",
      "\u001b[31mModuleNotFoundError\u001b[39m: No module named 'requests'"
     ]
    }
   ],
   "source": [
    "\n",
    "# ============================================================\n",
    "# 1. OBTENCIÓN DE LOS DATOS\n",
    "# ============================================================\n",
    "\n",
    "url_datos = (\n",
    "    \"https://ourworldindata.org/grapher/life-expectancy.csv\"\n",
    "    \"?v=1&csvType=full&useColumnShortNames=true\"\n",
    ")\n",
    "\n",
    "df = pd.read_csv(\n",
    "    url_datos,\n",
    "    storage_options={\n",
    "        \"User-Agent\": \"Our World In Data data fetch/1.0\"\n",
    "    }\n",
    ")\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# 2. OBTENCIÓN DE LOS METADATOS\n",
    "# ============================================================\n",
    "\n",
    "url_metadata = (\n",
    "    \"https://ourworldindata.org/grapher/life-expectancy.metadata.json\"\n",
    "    \"?v=1&csvType=full&useColumnShortNames=true\"\n",
    ")\n",
    "\n",
    "metadata = requests.get(url_metadata).json()\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# 3. FUNCIÓN DEL PIPELINE\n",
    "# ============================================================\n",
    "\n",
    "def ejecutar_pipeline(df):\n",
    "\n",
    "    print(\"============================================\")\n",
    "    print(\"INICIO DEL PIPELINE\")\n",
    "    print(\"============================================\")\n",
    "\n",
    "    # --------------------------------------------------------\n",
    "    # 3.1 Dimensiones iniciales\n",
    "    # --------------------------------------------------------\n",
    "\n",
    "    print(\"\\nDimensiones iniciales:\")\n",
    "    print(df.shape)\n",
    "\n",
    "    # --------------------------------------------------------\n",
    "    # 3.2 Identificar las columnas disponibles\n",
    "    # --------------------------------------------------------\n",
    "\n",
    "    print(\"\\nColumnas disponibles:\")\n",
    "    print(df.columns.tolist())\n",
    "\n",
    "    # --------------------------------------------------------\n",
    "    # 3.3 Tipos de datos\n",
    "    # --------------------------------------------------------\n",
    "\n",
    "    print(\"\\nTipos de datos:\")\n",
    "    print(df.dtypes)\n",
    "\n",
    "    # --------------------------------------------------------\n",
    "    # 3.4 Valores nulos\n",
    "    # --------------------------------------------------------\n",
    "\n",
    "    print(\"\\nValores nulos:\")\n",
    "    print(df.isnull().sum())\n",
    "\n",
    "    # --------------------------------------------------------\n",
    "    # 3.5 Eliminar filas con valores nulos\n",
    "    # --------------------------------------------------------\n",
    "\n",
    "    df = df.dropna()\n",
    "\n",
    "    print(\"\\nDimensiones después de eliminar nulos:\")\n",
    "    print(df.shape)\n",
    "\n",
    "    # --------------------------------------------------------\n",
    "    # 3.6 Eliminar posibles filas duplicadas\n",
    "    # --------------------------------------------------------\n",
    "\n",
    "    df = df.drop_duplicates()\n",
    "\n",
    "    print(\"\\nDimensiones después de eliminar duplicados:\")\n",
    "    print(df.shape)\n",
    "\n",
    "    # --------------------------------------------------------\n",
    "    # 3.7 Resultado\n",
    "    # --------------------------------------------------------\n",
    "\n",
    "    archivo_salida = (\n",
    "        \"data/processed/\"\n",
    "        \"auto_resultado.csv\"\n",
    "    )\n",
    "\n",
    "    df.to_csv(\n",
    "        archivo_salida,\n",
    "        index=False\n",
    "    )\n",
    "\n",
    "    print(\"\\n============================================\")\n",
    "    print(\"PIPELINE FINALIZADO\")\n",
    "    print(\"============================================\")\n",
    "\n",
    "    print(f\"\\nArchivo generado:\")\n",
    "    print(archivo_salida)\n",
    "\n",
    "    return df\n",
    "\n",
    "\n",
    "# ============================================================\n",
    "# 4. EJECUCIÓN DEL PIPELINE\n",
    "# ============================================================\n",
    "\n",
    "df_procesado = ejecutar_pipeline(df)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": ".venv (3.13.3.final.0)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
